export const BSE_STATE_CODES = [
  { stateCode: "AN", stateName: "Andaman & Nicobar" },
  { stateCode: "AR", stateName: "Arunachal Pradesh" },
  { stateCode: "AP", stateName: "Andhra Pradesh" },
  { stateCode: "AS", stateName: "Assam" },
  { stateCode: "BH", stateName: "Bihar" },
  { stateCode: "CH", stateName: "Chandigarh" },
  { stateCode: "CG", stateName: "Chhattisgarh" },
  { stateCode: "GO", stateName: "GOA" },
  { stateCode: "GU", stateName: "Gujarat" },
  { stateCode: "HA", stateName: "Haryana" },
  { stateCode: "HP", stateName: "Himachal Pradesh" },
  { stateCode: "JM", stateName: "Jammu & Kashmir" },
  { stateCode: "JK", stateName: "Jharkhand" },
  { stateCode: "KA", stateName: "Karnataka" },
  { stateCode: "KE", stateName: "Kerala" },
  { stateCode: "MP", stateName: "Madhya Pradesh" },
  { stateCode: "MA", stateName: "Maharashtra" },
  { stateCode: "MN", stateName: "Manipur" },
  { stateCode: "ME", stateName: "Meghalaya" },
  { stateCode: "MI", stateName: "Mizoram" },
  { stateCode: "NA", stateName: "Nagaland" },
  { stateCode: "ND", stateName: "New Delhi" },
  { stateCode: "OR", stateName: "Orissa" },
  { stateCode: "PO", stateName: "Pondicherry" },
  { stateCode: "PU", stateName: "Punjab" },
  { stateCode: "RA", stateName: "Rajasthan" },
  { stateCode: "SI", stateName: "Sikkim" },
  { stateCode: "TG", stateName: "Telengana" },
  { stateCode: "TN", stateName: "Tamil Nadu" },
  { stateCode: "TR", stateName: "Tripura" },
  { stateCode: "UP", stateName: "Uttar Pradesh" },
  { stateCode: "UC", stateName: "Uttaranchal" },
  { stateCode: "WB", stateName: "West Bengal" },
  { stateCode: "DN", stateName: "Dadra and Nagar Haveli" },
  { stateCode: "DD", stateName: "Daman and Diu" },
  { stateCode: "LD", stateName: "Lakshadweep" },
  { stateCode: "OH", stateName: "Others" },
];

export const BSE_COUNTRY_CODE = [
  // BSE AND SIGNZY COUNTRIES ARE THE SAME EXCEPT FOR THE MISSING LAST 2 IN SIGNZY
  { countryCode: "001", countryName: "Afghanistan" },
  { countryCode: "002", countryName: "Aland Islands" },
  { countryCode: "003", countryName: "Albania" },
  { countryCode: "004", countryName: "Algeria" },
  { countryCode: "005", countryName: "American Samoa" },
  { countryCode: "006", countryName: "Andorra" },
  { countryCode: "007", countryName: "Angola" },
  { countryCode: "008", countryName: "Anguilla" },
  { countryCode: "009", countryName: "Antarctica" },
  { countryCode: "010", countryName: "Antigua And Barbuda" },
  { countryCode: "011", countryName: "Argentina" },
  { countryCode: "012", countryName: "Armenia" },
  { countryCode: "013", countryName: "Aruba" },
  { countryCode: "014", countryName: "Australia" },
  { countryCode: "015", countryName: "Austria" },
  { countryCode: "016", countryName: "Azerbaijan" },
  { countryCode: "017", countryName: "Bahamas" },
  { countryCode: "018", countryName: "Bahrain" },
  { countryCode: "019", countryName: "Bangladesh" },
  { countryCode: "020", countryName: "Barbados" },
  { countryCode: "021", countryName: "Belarus" },
  { countryCode: "022", countryName: "Belgium" },
  { countryCode: "023", countryName: "Belize" },
  { countryCode: "024", countryName: "Benin" },
  { countryCode: "025", countryName: "Bermuda" },
  { countryCode: "026", countryName: "Bhutan" },
  { countryCode: "027", countryName: "Bolivia" },
  { countryCode: "028", countryName: "Bosnia And Herzegovina" },
  { countryCode: "029", countryName: "Botswana" },
  { countryCode: "030", countryName: "Bouvet Island" },
  { countryCode: "031", countryName: "Brazil" },
  { countryCode: "032", countryName: "British Indian Ocean Territory" },
  { countryCode: "033", countryName: "Brunei Darussalam" },
  { countryCode: "034", countryName: "Bulgaria" },
  { countryCode: "035", countryName: "Burkina Faso" },
  { countryCode: "036", countryName: "Burundi" },
  { countryCode: "037", countryName: "Cambodia" },
  { countryCode: "038", countryName: "Cameroon" },
  { countryCode: "039", countryName: "Canada" },
  { countryCode: "040", countryName: "Cape Verde" },
  { countryCode: "041", countryName: "Cayman Islands" },
  { countryCode: "042", countryName: "Central African Republic" },
  { countryCode: "043", countryName: "Chad" },
  { countryCode: "044", countryName: "Chile" },
  { countryCode: "045", countryName: "China" },
  { countryCode: "046", countryName: "Christmas Island" },
  { countryCode: "047", countryName: "Cocos (Keeling) Islands" },
  { countryCode: "048", countryName: "Colombia" },
  { countryCode: "049", countryName: "Comoros" },
  { countryCode: "050", countryName: "Congo" },
  { countryCode: "051", countryName: "Congo, The Democratic Republic Of The" },
  { countryCode: "052", countryName: "Cook Islands" },
  { countryCode: "053", countryName: "Costa Rica" },
  { countryCode: "054", countryName: "Cote DIvoire" },
  { countryCode: "055", countryName: "Croatia" },
  { countryCode: "056", countryName: "Cuba" },
  { countryCode: "057", countryName: "Cyprus" },
  { countryCode: "058", countryName: "Czech Republic" },
  { countryCode: "059", countryName: "Denmark" },
  { countryCode: "060", countryName: "Djibouti" },
  { countryCode: "061", countryName: "Dominica" },
  { countryCode: "062", countryName: "Dominican Republic" },
  { countryCode: "063", countryName: "Ecuador" },
  { countryCode: "064", countryName: "Egypt" },
  { countryCode: "065", countryName: "El Salvador" },
  { countryCode: "066", countryName: "Equatorial Guinea" },
  { countryCode: "067", countryName: "Eritrea" },
  { countryCode: "068", countryName: "Estonia" },
  { countryCode: "069", countryName: "Ethiopia" },
  { countryCode: "070", countryName: "Falkland Islands (Malvinas)" },
  { countryCode: "071", countryName: "Faroe Islands" },
  { countryCode: "072", countryName: "Fiji" },
  { countryCode: "073", countryName: "Finland" },
  { countryCode: "074", countryName: "France" },
  { countryCode: "075", countryName: "French Guiana" },
  { countryCode: "076", countryName: "French Polynesia" },
  { countryCode: "077", countryName: "French Southern Territories" },
  { countryCode: "078", countryName: "Gabon" },
  { countryCode: "079", countryName: "Gambia" },
  { countryCode: "080", countryName: "Georgia" },
  { countryCode: "081", countryName: "Germany" },
  { countryCode: "082", countryName: "Ghana" },
  { countryCode: "083", countryName: "Gibraltar" },
  { countryCode: "084", countryName: "Greece" },
  { countryCode: "085", countryName: "Greenland" },
  { countryCode: "086", countryName: "Grenada" },
  { countryCode: "087", countryName: "Guadeloupe" },
  { countryCode: "088", countryName: "Guam" },
  { countryCode: "089", countryName: "Guatemala" },
  { countryCode: "090", countryName: "Guernsey" },
  { countryCode: "091", countryName: "Guinea" },
  { countryCode: "092", countryName: "Guinea-Bissau" },
  { countryCode: "093", countryName: "Guyana" },
  { countryCode: "094", countryName: "Haiti" },
  { countryCode: "095", countryName: "Heard Island And Mcdonald Islands" },
  { countryCode: "096", countryName: "Holy See (Vatican City State)" },
  { countryCode: "097", countryName: "Honduras" },
  { countryCode: "098", countryName: "Hong Kong" },
  { countryCode: "099", countryName: "Hungary" },
  { countryCode: "100", countryName: "Iceland" },
  { countryCode: "101", countryName: "India" },
  { countryCode: "102", countryName: "Indonesia" },
  // { countryCode: "103", countryName: "Iran, Islamic Republic Of" },
  { countryCode: "103", countryName: "Iran" },
  { countryCode: "104", countryName: "Iraq" },
  { countryCode: "105", countryName: "Ireland" },
  { countryCode: "106", countryName: "Isle Of Man" },
  { countryCode: "107", countryName: "Israel" },
  { countryCode: "108", countryName: "Italy" },
  { countryCode: "109", countryName: "Jamaica" },
  { countryCode: "110", countryName: "Japan" },
  { countryCode: "111", countryName: "Jersey" },
  { countryCode: "112", countryName: "Jordan" },
  { countryCode: "113", countryName: "Kazakhstan" },
  { countryCode: "114", countryName: "Kenya" },
  { countryCode: "115", countryName: "Kiribati" },
  { countryCode: "116", countryName: "Korea, Democratic Peoples Republic Of" },
  { countryCode: "117", countryName: "Korea, Republic Of" },
  { countryCode: "118", countryName: "Kuwait" },
  { countryCode: "119", countryName: "Kyrgyzstan" },
  { countryCode: "120", countryName: "Lao Peoples Democratic Republic" },
  { countryCode: "121", countryName: "Latvia" },
  { countryCode: "122", countryName: "Lebanon" },
  { countryCode: "123", countryName: "Lesotho" },
  { countryCode: "124", countryName: "Liberia" },
  { countryCode: "125", countryName: "Libyan Arab Jamahiriya" },
  { countryCode: "126", countryName: "Liechtenstein" },
  { countryCode: "127", countryName: "Lithuania" },
  { countryCode: "128", countryName: "Luxembourg" },
  { countryCode: "129", countryName: "Macao" },
  { countryCode: "130", countryName: "Macedonia, The Former Yugoslav Republic Of" },
  { countryCode: "131", countryName: "Madagascar" },
  { countryCode: "132", countryName: "Malawi" },
  { countryCode: "133", countryName: "Malaysia" },
  { countryCode: "134", countryName: "Maldives" },
  { countryCode: "135", countryName: "Mali" },
  { countryCode: "136", countryName: "Malta" },
  { countryCode: "137", countryName: "Marshall Islands" },
  { countryCode: "138", countryName: "Martinique" },
  { countryCode: "139", countryName: "Mauritania" },
  { countryCode: "140", countryName: "Mauritius" },
  { countryCode: "141", countryName: "Mayotte" },
  { countryCode: "142", countryName: "Mexico" },
  { countryCode: "143", countryName: "Micronesia, Federated States Of" },
  { countryCode: "144", countryName: "Moldova, Republic Of" },
  { countryCode: "145", countryName: "Monaco" },
  { countryCode: "146", countryName: "Mongolia" },
  { countryCode: "147", countryName: "Montserrat" },
  { countryCode: "148", countryName: "Morocco" },
  { countryCode: "149", countryName: "Mozambique" },
  { countryCode: "150", countryName: "Myanmar" },
  { countryCode: "151", countryName: "Namibia" },
  { countryCode: "152", countryName: "Nauru" },
  { countryCode: "153", countryName: "Nepal" },
  { countryCode: "154", countryName: "Netherlands" },
  { countryCode: "155", countryName: "Netherlands Antilles" },
  { countryCode: "156", countryName: "New Caledonia" },
  { countryCode: "157", countryName: "New Zealand" },
  { countryCode: "158", countryName: "Nicaragua" },
  { countryCode: "159", countryName: "Niger" },
  { countryCode: "160", countryName: "Nigeria" },
  { countryCode: "161", countryName: "Niue" },
  { countryCode: "162", countryName: "Norfolk Island" },
  { countryCode: "163", countryName: "Northern Mariana Islands" },
  { countryCode: "164", countryName: "Norway" },
  { countryCode: "165", countryName: "Oman" },
  { countryCode: "166", countryName: "Pakistan" },
  { countryCode: "167", countryName: "Palau" },
  { countryCode: "168", countryName: "Palestinian Territory, Occupied" },
  { countryCode: "169", countryName: "Panama" },
  { countryCode: "170", countryName: "Papua New Guinea" },
  { countryCode: "171", countryName: "Paraguay" },
  { countryCode: "172", countryName: "Peru" },
  { countryCode: "173", countryName: "Philippines" },
  { countryCode: "174", countryName: "Pitcairn" },
  { countryCode: "175", countryName: "Poland" },
  { countryCode: "176", countryName: "Portugal" },
  { countryCode: "177", countryName: "Puerto Rico" },
  { countryCode: "178", countryName: "Qatar" },
  { countryCode: "179", countryName: "Reunion" },
  { countryCode: "180", countryName: "Romania" },
  { countryCode: "181", countryName: "Russian Federation" },
  { countryCode: "182", countryName: "Rwanda" },
  { countryCode: "183", countryName: "Saint Helena" },
  { countryCode: "184", countryName: "Saint Kitts And Nevis" },
  { countryCode: "185", countryName: "Saint Lucia" },
  { countryCode: "186", countryName: "Saint Pierre And Miquelon" },
  { countryCode: "187", countryName: "Saint Vincent And The Grenadines" },
  { countryCode: "188", countryName: "Samoa" },
  { countryCode: "189", countryName: "San Marino" },
  { countryCode: "190", countryName: "Sao Tome And Principe" },
  { countryCode: "191", countryName: "Saudi Arabia" },
  { countryCode: "192", countryName: "Senegal" },
  { countryCode: "193", countryName: "Serbia And Montenegro" },
  { countryCode: "194", countryName: "Seychelles" },
  { countryCode: "195", countryName: "Sierra Leone" },
  { countryCode: "196", countryName: "Singapore" },
  { countryCode: "197", countryName: "Slovakia" },
  { countryCode: "198", countryName: "Slovenia" },
  { countryCode: "199", countryName: "Solomon Islands" },
  { countryCode: "200", countryName: "Somalia" },
  { countryCode: "201", countryName: "South Africa" },
  { countryCode: "202", countryName: "South Georgia And The South Sandwich Islands" },
  { countryCode: "203", countryName: "Spain" },
  { countryCode: "204", countryName: "Sri Lanka" },
  { countryCode: "205", countryName: "Sudan" },
  { countryCode: "206", countryName: "Suriname" },
  { countryCode: "207", countryName: "Svalbard And Jan Mayen" },
  { countryCode: "208", countryName: "Swaziland" },
  { countryCode: "209", countryName: "Sweden" },
  { countryCode: "210", countryName: "Switzerland" },
  { countryCode: "211", countryName: "Syrian Arab Republic" },
  { countryCode: "212", countryName: "Taiwan, Province Of China" },
  { countryCode: "213", countryName: "Tajikistan" },
  { countryCode: "214", countryName: "Tanzania, United Republic Of" },
  { countryCode: "215", countryName: "Thailand" },
  { countryCode: "216", countryName: "Timor-Leste" },
  { countryCode: "217", countryName: "Togo" },
  { countryCode: "218", countryName: "Tokelau" },
  { countryCode: "219", countryName: "Tonga" },
  { countryCode: "220", countryName: "Trinidad And Tobago" },
  { countryCode: "221", countryName: "Tunisia" },
  { countryCode: "222", countryName: "Turkey" },
  { countryCode: "223", countryName: "Turkmenistan" },
  { countryCode: "224", countryName: "Turks And Caicos Islands" },
  { countryCode: "225", countryName: "Tuvalu" },
  { countryCode: "226", countryName: "Uganda" },
  { countryCode: "227", countryName: "Ukraine" },
  { countryCode: "228", countryName: "United Arab Emirates" },
  { countryCode: "229", countryName: "United Kingdom" },
  { countryCode: "230", countryName: "United States of America" },
  { countryCode: "231", countryName: "United States Minor Outlying Islands" },
  { countryCode: "232", countryName: "Uruguay" },
  { countryCode: "233", countryName: "Uzbekistan" },
  { countryCode: "234", countryName: "Vanuatu" },
  { countryCode: "235", countryName: "Venezuela" },
  { countryCode: "236", countryName: "Viet Nam" },
  { countryCode: "237", countryName: "Virgin Islands, British" },
  { countryCode: "238", countryName: "Virgin Islands, U.S." },
  { countryCode: "239", countryName: "Wallis And Futuna" },
  { countryCode: "240", countryName: "Western Sahara" },
  { countryCode: "241", countryName: "Yemen" },
  { countryCode: "242", countryName: "Zambia" },
  { countryCode: "243", countryName: "Zimbabwe" },
];

export const BSE_TAX_STATUS = [
  { code: "01", name: "Individual", account: ["SB", "CB"] },
  { code: "02", name: "On behalf of minor", account: ["SB", "CB"] },
  { code: "03", name: "HUF", account: ["SB", "CB"] },
  { code: "04", name: "Company", account: ["CB"] },
  { code: "05", name: "AOP", account: ["CB"] },
  { code: "06", name: "Partnership Firm", account: ["CB"] },
  { code: "07", name: "Body Corporate", account: ["CB"] },
  { code: "08", name: "Trust", account: ["CB"] },
  { code: "09", name: "Society", account: ["CB"] },
  { code: "10", name: "Others", account: ["CB"] },
  { code: "11", name: "NRI-Others", account: ["NE", "NO"] },
  { code: "12", name: "DIF", account: ["CB"] },
  { code: "13", name: "Sole Proprietorship", account: ["SB", "CB"] },
  { code: "21", name: "NRE", account: ["NE"] },
  { code: "22", name: "OCB", account: ["CB"] },
  { code: "23", name: "FII", account: ["NE", "NO"] },
  { code: "24", name: "NRO", account: ["NO"] },
  { code: "25", name: "Overseas Corp. Body - Others", account: ["NE", "NO"] },
  { code: "26", name: "NRI Child", account: ["NE", "NO"] },
  { code: "27", name: "NRI - HUF (NRO)", account: ["NO"] },
  { code: "28", name: "NRI - Minor (NRO)", account: ["NO"] },
  { code: "29", name: "NRI - HUF (NRE)", account: ["NE"] },
  { code: "31", name: "Provident Fund", account: ["CB"] },
  { code: "32", name: "Super Annuation Fund", account: ["CB"] },
  { code: "33", name: "Gratuity Fund", account: ["CB"] },
  { code: "34", name: "Pension Fund", account: ["CB"] },
  { code: "36", name: "Mutual Funds FOF Schemes", account: ["CB"] },
  { code: "37", name: "NPS Trust", account: ["CB"] },
  { code: "38", name: "Global Development Network", account: ["NE", "NO"] },
  { code: "39", name: "FCRA", account: ["NE", "NO"] },
  { code: "41", name: "QFI - Individual", account: ["NE", "NO"] },
  { code: "42", name: "QFI - Minors", account: ["NE", "NO"] },
  { code: "43", name: "QFI - Corporate", account: ["CB"] },
  { code: "44", name: "QFI - Pension Funds", account: ["CB"] },
  { code: "45", name: "QFI - Hedge Funds", account: ["CB"] },
  { code: "46", name: "QFI - Mutual Funds", account: ["CB"] },
  { code: "47", name: "LLP", account: ["CB"] },
  { code: "48", name: "Non-Profit organization [NPO]", account: ["CB"] },
  { code: "51", name: "Public Limited Company", account: ["CB"] },
  { code: "52", name: "Private Limited Company", account: ["CB"] },
  { code: "53", name: "Unlisted Company", account: ["CB"] },
  { code: "54", name: "Mutual Funds", account: ["CB"] },
  { code: "55", name: "FPI - Category I", account: ["NE", "NO"] },
  { code: "56", name: "FPI - Category II", account: ["NE", "NO"] },
  { code: "57", name: "FPI - Category III", account: ["NE", "NO"] },
  { code: "58", name: "Financial Institutions", account: ["CB"] },
  { code: "59", name: "Body of Individuals", account: ["CB"] },
  { code: "60", name: "Insurance Company", account: ["CB"] },
  { code: "61", name: "OCI - Repatriation", account: ["NE"] },
  { code: "62", name: "OCI - Non Repatriation", account: ["NO"] },
  { code: "70", name: "Person of Indian Origin", account: ["NE", "NO"] },
  { code: "72", name: "Government Body", account: ["CB"] },
  { code: "73", name: "Defense Establishment", account: ["CB"] },
  { code: "74", name: "Non - Government Organisation", account: ["CB"] },
  { code: "75", name: "Bank/Co-Operative Bank", account: ["CB"] },
  { code: "76", name: "Seafarer NRE", account: ["NE"] },
  { code: "77", name: "Seafarer NRO", account: ["NO"] },
];

export const BSE_HOLDING_NATURE = [
  { code: "SI", name: "Single" },
  { code: "JO", name: "Joint" },
  { code: "AS", name: "Anyone Or Survivor" },
];

export const BSE_ACCOUNT_TYPE = [
  { code: "SB", name: "Savings Bank" },
  { code: "CB", name: "Current Bank" },
  { code: "NE", name: "NRE" },
  { code: "NO", name: "NRO" },
];
// SB
// Savings Bank
// Current Bank
// CB
