export const SIGNZY_INCOME_RANGE = [
  { name: "Below 1 Lac", code: 31 },
  { name: "1-5 Lacs", code: 32 },
  { name: "5-10 Lacs", code: 33 },
  { name: "10-25 Lacs", code: 34 },
  { name: "25 Lacs-1 crore", code: 35 },
  { name: "1 crore", code: 36 },
];

export const SIGNZY_USERNAME = "tataamc_niveshonline_preprod";
export const SIGNZY_PASSWORD = "jdi96MdhtQ!3$wueMShdPD83Dh@3";

export const SIGNZY_COUNTRY_ARR = [
  // BSE AND SIGNZY COUNTRIES ARE THE SAME EXCEPT FOR THE MISSING LAST 2 IN SIGNZY
  { Code: "101", Country: "India" },
  { Code: "001", Country: "Afghanistan" },
  { Code: "002", Country: "Aland Islands" },
  { Code: "003", Country: "Albania" },
  { Code: "004", Country: "Algeria" },
  { Code: "005", Country: "American Samoa" },
  { Code: "006", Country: "Andorra" },
  { Code: "007", Country: "Angola" },
  { Code: "008", Country: "Anguilla" },
  { Code: "009", Country: "Antarctica" },
  { Code: "010", Country: "Antigua And Barbuda" },
  { Code: "011", Country: "Argentina" },
  { Code: "012", Country: "Armenia" },
  { Code: "013", Country: "Aruba" },
  { Code: "014", Country: "Australia" },
  { Code: "015", Country: "Austria" },
  { Code: "016", Country: "Azerbaijan" },
  { Code: "017", Country: "Bahamas" },
  { Code: "018", Country: "Bahrain" },
  { Code: "019", Country: "Bangladesh" },
  { Code: "020", Country: "Barbados" },
  { Code: "021", Country: "Belarus" },
  { Code: "022", Country: "Belgium" },
  { Code: "023", Country: "Belize" },
  { Code: "024", Country: "Benin" },
  { Code: "025", Country: "Bermuda" },
  { Code: "026", Country: "Bhutan" },
  { Code: "027", Country: "Bolivia" },
  { Code: "028", Country: "Bosnia And Herzegovina" },
  { Code: "029", Country: "Botswana" },
  { Code: "030", Country: "Bouvet Island" },
  { Code: "031", Country: "Brazil" },
  { Code: "032", Country: "British Indian Ocean Territory" },
  { Code: "033", Country: "Brunei Darussalam" },
  { Code: "034", Country: "Bulgaria" },
  { Code: "035", Country: "Burkina Faso" },
  { Code: "036", Country: "Burundi" },
  { Code: "037", Country: "Cambodia" },
  { Code: "038", Country: "Cameroon" },
  { Code: "039", Country: "Canada" },
  { Code: "040", Country: "Cape Verde" },
  { Code: "041", Country: "Cayman Islands" },
  { Code: "042", Country: "Central African Republic" },
  { Code: "043", Country: "Chad" },
  { Code: "044", Country: "Chile" },
  { Code: "045", Country: "China" },
  { Code: "046", Country: "Christmas Island" },
  { Code: "047", Country: "Cocos (Keeling) Islands" },
  { Code: "048", Country: "Colombia" },
  { Code: "049", Country: "Comoros" },
  { Code: "050", Country: "Congo" },
  { Code: "051", Country: "Congo, The Democratic Republic Of The" },
  { Code: "052", Country: "Cook Islands" },
  { Code: "053", Country: "Costa Rica" },
  { Code: "054", Country: "Cote D'Ivoire" },
  { Code: "055", Country: "Croatia" },
  { Code: "056", Country: "Cuba" },
  { Code: "057", Country: "Cyprus" },
  { Code: "058", Country: "Czech Republic" },
  { Code: "059", Country: "Denmark" },
  { Code: "060", Country: "Djibouti" },
  { Code: "061", Country: "Dominica" },
  { Code: "062", Country: "Dominican Republic" },
  { Code: "063", Country: "Ecuador" },
  { Code: "064", Country: "Egypt" },
  { Code: "065", Country: "El Salvador" },
  { Code: "066", Country: "Equatorial Guinea" },
  { Code: "067", Country: "Eritrea" },
  { Code: "068", Country: "Estonia" },
  { Code: "069", Country: "Ethiopia" },
  { Code: "070", Country: "Falkland Islands (Malvinas)" },
  { Code: "071", Country: "Faroe Islands" },
  { Code: "072", Country: "Fiji" },
  { Code: "073", Country: "Finland" },
  { Code: "074", Country: "France" },
  { Code: "075", Country: "French Guiana" },
  { Code: "076", Country: "French Polynesia" },
  { Code: "077", Country: "French Southern Territories" },
  { Code: "078", Country: "Gabon" },
  { Code: "079", Country: "Gambia" },
  { Code: "080", Country: "Georgia" },
  { Code: "081", Country: "Germany" },
  { Code: "082", Country: "Ghana" },
  { Code: "083", Country: "Gibraltar" },
  { Code: "084", Country: "Greece" },
  { Code: "085", Country: "Greenland" },
  { Code: "086", Country: "Grenada" },
  { Code: "087", Country: "Guadeloupe" },
  { Code: "088", Country: "Guam" },
  { Code: "089", Country: "Guatemala" },
  { Code: "090", Country: "Guernsey" },
  { Code: "091", Country: "Guinea" },
  { Code: "092", Country: "Guinea-Bissau" },
  { Code: "093", Country: "Guyana" },
  { Code: "094", Country: "Haiti" },
  { Code: "095", Country: "Heard Island And Mcdonald Islands" },
  { Code: "096", Country: "Holy See (Vatican City State)" },
  { Code: "097", Country: "Honduras" },
  { Code: "098", Country: "Hong Kong" },
  { Code: "099", Country: "Hungary" },
  { Code: "100", Country: "Iceland" },
  { Code: "102", Country: "Indonesia" },
  { Code: "103", Country: "Iran, Islamic Republic Of" },
  { Code: "104", Country: "Iraq" },
  { Code: "105", Country: "Ireland" },
  { Code: "106", Country: "Isle Of Man" },
  { Code: "107", Country: "Israel" },
  { Code: "108", Country: "Italy" },
  { Code: "109", Country: "Jamaica" },
  { Code: "110", Country: "Japan" },
  { Code: "111", Country: "Jersey" },
  { Code: "112", Country: "Jordan" },
  { Code: "113", Country: "Kazakhstan" },
  { Code: "114", Country: "Kenya" },
  { Code: "115", Country: "Kiribati" },
  { Code: "116", Country: "Korea, Democratic People’s Republic Of" },
  { Code: "117", Country: "Korea, Republic Of" },
  { Code: "118", Country: "Kuwait" },
  { Code: "119", Country: "Kyrgyzstan" },
  { Code: "120", Country: "Lao People’s Democratic Republic" },
  { Code: "121", Country: "Latvia" },
  { Code: "122", Country: "Lebanon" },
  { Code: "123", Country: "Lesotho" },
  { Code: "124", Country: "Liberia" },
  { Code: "125", Country: "Libyan Arab Jamahiriya" },
  { Code: "126", Country: "Liechtenstein" },
  { Code: "127", Country: "Lithuania" },
  { Code: "128", Country: "Luxembourg" },
  { Code: "129", Country: "Macao" },
  { Code: "130", Country: "Macedonia, The Former Yugoslav Republic Of" },
  { Code: "131", Country: "Madagascar" },
  { Code: "132", Country: "Malawi" },
  { Code: "133", Country: "Malaysia" },
  { Code: "134", Country: "Maldives" },
  { Code: "135", Country: "Mali" },
  { Code: "136", Country: "Malta" },
  { Code: "137", Country: "Marshall Islands" },
  { Code: "138", Country: "Martinique" },
  { Code: "139", Country: "Mauritania" },
  { Code: "140", Country: "Mauritius" },
  { Code: "141", Country: "Mayotte" },
  { Code: "142", Country: "Mexico" },
  { Code: "143", Country: "Micronesia, Federated States Of" },
  { Code: "144", Country: "Moldova, Republic Of" },
  { Code: "145", Country: "Monaco" },
  { Code: "146", Country: "Mongolia" },
  { Code: "147", Country: "Montserrat" },
  { Code: "148", Country: "Morocco" },
  { Code: "149", Country: "Mozambique" },
  { Code: "150", Country: "Myanmar" },
  { Code: "151", Country: "Namibia" },
  { Code: "152", Country: "Nauru" },
  { Code: "153", Country: "Nepal" },
  { Code: "154", Country: "Netherlands" },
  { Code: "155", Country: "Netherlands Antilles" },
  { Code: "156", Country: "New Caledonia" },
  { Code: "157", Country: "New Zealand" },
  { Code: "158", Country: "Nicaragua" },
  { Code: "159", Country: "Niger" },
  { Code: "160", Country: "Nigeria" },
  { Code: "161", Country: "Niue" },
  { Code: "162", Country: "Norfolk Island" },
  { Code: "163", Country: "Northern Mariana Islands" },
  { Code: "164", Country: "Norway" },
  { Code: "165", Country: "Oman" },
  { Code: "166", Country: "Pakistan" },
  { Code: "167", Country: "Palau" },
  { Code: "168", Country: "Palestinian Territory, Occupied" },
  { Code: "169", Country: "Panama" },
  { Code: "170", Country: "Papua New Guinea" },
  { Code: "171", Country: "Paraguay" },
  { Code: "172", Country: "Peru" },
  { Code: "173", Country: "Philippines" },
  { Code: "174", Country: "Pitcairn" },
  { Code: "175", Country: "Poland" },
  { Code: "176", Country: "Portugal" },
  { Code: "177", Country: "Puerto Rico" },
  { Code: "178", Country: "Qatar" },
  { Code: "179", Country: "Reunion" },
  { Code: "180", Country: "Romania" },
  { Code: "181", Country: "Russian Federation" },
  { Code: "182", Country: "Rwanda" },
  { Code: "183", Country: "Saint Helena" },
  { Code: "184", Country: "Saint Kitts And Nevis" },
  { Code: "185", Country: "Saint Lucia" },
  { Code: "186", Country: "Saint Pierre And Miquelon" },
  { Code: "187", Country: "Saint Vincent And The Grenadines" },
  { Code: "188", Country: "Samoa" },
  { Code: "189", Country: "San Marino" },
  { Code: "190", Country: "Sao Tome And Principe" },
  { Code: "191", Country: "Saudi Arabia" },
  { Code: "192", Country: "Senegal" },
  { Code: "193", Country: "Serbia And Montenegro" },
  { Code: "194", Country: "Seychelles" },
  { Code: "195", Country: "Sierra Leone" },
  { Code: "196", Country: "Singapore" },
  { Code: "197", Country: "Slovakia" },
  { Code: "198", Country: "Slovenia" },
  { Code: "199", Country: "Solomon Islands" },
  { Code: "200", Country: "Somalia" },
  { Code: "201", Country: "South Africa" },
  { Code: "202", Country: "South Georgia And The South Sandwich Islands" },
  { Code: "203", Country: "Spain" },
  { Code: "204", Country: "Sri Lanka" },
  { Code: "205", Country: "Sudan" },
  { Code: "206", Country: "Suriname" },
  { Code: "207", Country: "Svalbard And Jan Mayen" },
  { Code: "208", Country: "Swaziland" },
  { Code: "209", Country: "Sweden" },
  { Code: "210", Country: "Switzerland" },
  { Code: "211", Country: "Syrian Arab Republic" },
  { Code: "212", Country: "Taiwan, Province Of China" },
  { Code: "213", Country: "Tajikistan" },
  { Code: "214", Country: "Tanzania, United Republic Of" },
  { Code: "215", Country: "Thailand" },
  { Code: "216", Country: "Timor-Leste" },
  { Code: "217", Country: "Togo" },
  { Code: "218", Country: "Tokelau" },
  { Code: "219", Country: "Tonga" },
  { Code: "220", Country: "Trinidad And Tobago" },
  { Code: "221", Country: "Tunisia" },
  { Code: "222", Country: "Turkey" },
  { Code: "223", Country: "Turkmenistan" },
  { Code: "224", Country: "Turks And Caicos Islands" },
  { Code: "225", Country: "Tuvalu" },
  { Code: "226", Country: "Uganda" },
  { Code: "227", Country: "Ukraine" },
  { Code: "228", Country: "United Arab Emirates" },
  { Code: "229", Country: "United Kingdom" },
  { Code: "230", Country: "United States" },
  { Code: "231", Country: "United States Minor Outlying Islands" },
  { Code: "232", Country: "Uruguay" },
  { Code: "233", Country: "Uzbekistan" },
  { Code: "234", Country: "Vanuatu" },
  { Code: "235", Country: "Venezuela" },
  { Code: "236", Country: "Viet Nam" },
  { Code: "237", Country: "Virgin Islands, British" },
  { Code: "238", Country: "Virgin Islands, U.S." },
  { Code: "239", Country: "Wallis And Futuna" },
  { Code: "240", Country: "Western Sahara" },
  { Code: "241", Country: "Yemen" },
  { Code: "242", Country: "Zambia" },
  { Code: "243", Country: "Zimbabwe" },
  { Code: "CI", Country: "Côte D'ivoire" },
  { Code: "KP", Country: "Korea,Democratic People'sRepublicOf" },
];
