import mongoose from "mongoose";
let Client = mongoose.Schema(
  {
    orgId: String,
    branchName: String,
    fullName: String,
    groupHeadName: String,
    userName: String,
    fatherOrSpouseName: String,
    mobileNo: String,
    emailId: String,
    dob: String,
    gender: String,
    maritalStatus: String,
    nationality: String,
    birthPlace: String,
    aadhaarNo: String,
    panNo: String,
    gstNo: String,
    educationalQualification: String,
    drivingLincenseNo: String,
    drivingLicenseExp: String,
    passportExp: String,
    passportNo: String,
    remarks: String,
    age: String,
    flatNo: String,
    street: String,
    area: String,
    city: String,
    pincode: String,
    state: String,
    country: String,
    telephoneNumberO: String,
    telephoneNumberR: String,
    otherNo: String,
    emailId2: String,
    faxNo: String,
    website: String,
    document: String,
    clientTitle: String,
    residence: String,
  },
  { timestamps: true }
);
export default mongoose.model("Client", Client);
